# Generated by Django 6.0 on 2026-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0008_alter_userdetails_userpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='usertype',
            field=models.CharField(choices=[('USER', 'User'), ('VENDOR', 'Vendor')], default='USER', max_length=100),
        ),
    ]
