# Generated by Django 6.0 on 2026-01-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0009_userdetails_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
