# Generated by Django 6.0 on 2026-01-21 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0005_remove_fooditems_category_fooditems_catogery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(blank=True, choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], max_length=100, null=True)),
                ('size', models.CharField(choices=[('regular', 'Regular'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('base', models.CharField(choices=[('maida', 'Maida'), ('wheat', 'Wheat')], max_length=10)),
                ('sauce', models.CharField(choices=[('mayo', 'Mayo'), ('red', 'Red')], max_length=10)),
                ('topping', models.CharField(choices=[('sweet_corn', 'Sweet Corn'), ('paneer', 'Paneer'), ('olive', 'Olive'), ('onion', 'Onion'), ('capsicum', 'Capsicum'), ('cheese', 'Cheese'), ('chicken', 'Chicken'), ('egg', 'Egg'), ('tomato', 'Tomato'), ('green_leaves', 'Green Leaves')], max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='foodsapp.fooditems')),
            ],
        ),
    ]
