# Generated by Django 6.0 on 2026-01-22 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0006_customizeoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuimg/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='foodsapp.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='SauceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuimg/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sauces', to='foodsapp.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size_cm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuimg/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='foodsapp.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='ToppingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuimg/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='foodsapp.fooditems')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomizeOption',
        ),
    ]
