# Generated by Django 6.0 on 2026-01-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0007_baseoption_sauceoption_sizeoption_toppingoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseoption',
            old_name='name',
            new_name='basetype',
        ),
        migrations.RenameField(
            model_name='sauceoption',
            old_name='name',
            new_name='sausetype',
        ),
        migrations.RenameField(
            model_name='sizeoption',
            old_name='name',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='toppingoption',
            old_name='name',
            new_name='toppingname',
        ),
    ]
