# Generated by Django 6.0 on 2026-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0008_rename_name_baseoption_basetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoption',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sauceoption',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppingoption',
            name='category',
            field=models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
