# Generated by Django 6.0 on 2026-01-22 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0009_baseoption_category_sauceoption_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('FRENCH FRIES', 'French Fries'), ('DESSARTS', 'Dessarts'), ('BREVERAGES', 'Breverages'), ('BRIYANI', 'Briyani')], max_length=100)),
                ('option_type', models.CharField(choices=[('SIZE', 'Size'), ('BASE', 'Base'), ('TOPPING', 'Topping'), ('SAUCE', 'Sauce')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('size_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cuimg/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_options', to='foodsapp.fooditems')),
            ],
        ),
    ]
