# Generated by Django 6.0 on 2026-01-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0010_customizedoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.fooditems')),
            ],
        ),
        migrations.CreateModel(
            name='CustomizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foodsapp.customization')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.customizedoption')),
            ],
        ),
    ]
