# Generated by Django 6.0 on 2026-01-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0011_customization_customizationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('foodimg', models.ImageField(blank=True, null=True, upload_to='foodimg/')),
                ('description', models.TextField()),
            ],
        ),
    ]
