# Generated by Django 6.0 on 2026-01-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0014_remove_cart_description_remove_cart_foodimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='food',
        ),
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
