# Generated by Django 6.0 on 2026-01-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0017_remove_cart_food_cart_description_cart_foodimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='cart/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
