# Generated by Django 6.0 on 2026-01-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0018_cart_base_price_cart_extra_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='extra_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='foodimg',
            field=models.ImageField(blank=True, null=True, upload_to='foodimg/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
