# Generated by Django 6.0 on 2026-05-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0023_order_razorpay_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
